version: '3.1'

############################# SERVICES #################################
services:
#database engine service
  postgres_db:
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    volumes:
        #allow *.sql, *.sql.gz, or *.sh and is execute only if data directory is empty
      - ./dbfiles:/docker-entrypoint-initdb.d
      - /var/lib/postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwerty
      POSTGRES_DB: postgres    


#database admin service
  adminer:
    image: adminer
    restart: always
    depends_on: 
      - postgres_db
    ports:
       - 9090:8080

#Billin app backend service
  billingapp-back:
    build:
      context: ./java
      args:
        - JAR_FILE=billing-0.0.3-SNAPSHOT.jar
    image: billingapp_v2-billingapp-back
    environment:
       - JAVA_OPTS=
         -Xms256M 
         -Xmx256M         
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    depends_on:     
      - postgres_db
    ports:
      - 8080:8080 

#Billin app frontend service
  billingapp-front:
    image: billingapp_v2-billingapp-front
    build:
      context: ./angular 
    deploy:   
        replicas: 3
        resources:
           limits: 
              cpus: "0.15"
              memory: 250M
                #recusos dedicados, mantiene los recursos disponibles del host para el contenedor
           reservations:
              cpus: "0.1"
              memory: 128M
    depends_on:     
      - billingapp-back
#rango de puertos para escalar    
    ports:
      - 80-85:80 


############################# NETWORKS ##################################
#networks:
#  env_prod:
#    driver: bridge
#    #activate ipv6
#    driver_opts:
#            com.docker.network.enable_ipv6: "true"
#    #IP address manager
#    ipam:
#      driver: default
#      config:
#      -
#        subnet: 172.16.232.0/24
#        gateway: 172.16.232.1
#      -
#        subnet: "2001:3974:3979::/64"
#        gateway: "2001:3974:3979::1"
#
#  env_prep:
#    driver: bridge
#    #activate ipv6
#    driver_opts:
#            com.docker.network.enable_ipv6: "true"
#    #IP address manager
#    ipam:
#      driver: default
#      config:
#      -
#        subnet: 172.16.235.0/24
#        gateway: 172.16.235.1
#      -
#        subnet: "2001:3984:3989::/64"
#        gateway: "2001:3984:3989::1"
