apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  labels:
    app: postgres
spec:
  replicas: 1
  # Define how the Deployment identifies the pods that it can manage
  selector:
    matchLabels:
      app: postgres
  # pod template specification
  template:
    metadata:
      # define labels for all pods
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          imagePullPolicy: IfNotPresent
          #open port to allow send and receive trafic in the container
          ports:
            - containerPort: 5432
          # read env vars from secret file
          envFrom:
            - secretRef:
                name: postgres-secret
          volumeMounts:
            # This is the path in the container on which the mounting will take place
            - mountPath: /var/lib/postgresque/data
              name: postgresdb
            - mountPath: /docker-entrypoint-initdb.d
              name: init-script
      volumes:
        - name: postgresdb
          persistentVolumeClaim: 
            claimName: postgres-claim
        - name: init-script
          configMap:
             name: postgres-init-script-configmap
